// AUTO-GENERATED from DomainIQ by scripts/domainiq/export-domainiq.py - do not edit by hand.
import type { DomainIQData } from "./types";

export const DOMAINIQ_DATA: DomainIQData = {
  "source": "DomainIQ app/services (generation + scoring), exported by scripts/domainiq/export-domainiq.py",
  "wordlists": {
    "premiumRoots": [
      "apex",
      "arc",
      "axis",
      "beam",
      "blue",
      "bolt",
      "bright",
      "clear",
      "core",
      "craft",
      "crest",
      "dash",
      "edge",
      "elevate",
      "ember",
      "flux",
      "forge",
      "fuse",
      "grid",
      "halo",
      "hive",
      "horizon",
      "ignite",
      "lift",
      "loom",
      "lumen",
      "mint",
      "nexus",
      "nova",
      "orbit",
      "peak",
      "prime",
      "pulse",
      "scale",
      "shift",
      "spark",
      "stride",
      "summit",
      "swift",
      "vault",
      "vertex",
      "vibe",
      "wave",
      "zenith",
      "aura",
      "luna",
      "sol",
      "vera",
      "nilo",
      "kairo",
      "orion",
      "lyra",
      "pico",
      "zara",
      "nava"
    ],
    "shortBusinessSuffixes": [
      "ly",
      "io",
      "ify",
      "hub",
      "base",
      "flow",
      "path",
      "link",
      "zone",
      "desk",
      "ora",
      "ivo"
    ],
    "longBusinessSuffixes": [
      "labs",
      "stack",
      "cloud",
      "works",
      "logic",
      "sense",
      "pilot",
      "forge",
      "grid",
      "suite"
    ],
    "businessPrefixes": [
      "get",
      "go",
      "try",
      "use",
      "my",
      "hey",
      "join",
      "meet",
      "run",
      "build"
    ],
    "trendWords": [
      "ai",
      "auto",
      "cloud",
      "cyber",
      "data",
      "dev",
      "digital",
      "fin",
      "health",
      "learn",
      "market",
      "meta",
      "micro",
      "neo",
      "open",
      "quantum",
      "smart",
      "sync",
      "tech",
      "trust"
    ],
    "industryTrendWords": {
      "technology": [
        "ai",
        "cloud",
        "dev",
        "stack",
        "sync",
        "data",
        "code",
        "byte"
      ],
      "saas": [
        "flow",
        "sync",
        "pilot",
        "ops",
        "dash",
        "launch",
        "stack",
        "hub"
      ],
      "ai": [
        "nova",
        "neural",
        "mind",
        "oracle",
        "sense",
        "prompt",
        "spark",
        "lumen"
      ],
      "finance": [
        "fin",
        "pay",
        "fund",
        "vault",
        "trust",
        "capital",
        "cash",
        "ledger"
      ],
      "fintech": [
        "pay",
        "vault",
        "ledger",
        "fund",
        "trust",
        "capital",
        "mint"
      ],
      "health": [
        "health",
        "care",
        "well",
        "vita",
        "med",
        "life",
        "pulse",
        "heal"
      ],
      "education": [
        "learn",
        "edu",
        "skill",
        "mind",
        "study",
        "course",
        "brain",
        "tutor"
      ],
      "commerce": [
        "shop",
        "cart",
        "market",
        "trade",
        "sell",
        "store",
        "buy",
        "deal"
      ],
      "crypto": [
        "vault",
        "chain",
        "mint",
        "node",
        "spark",
        "flux",
        "prime"
      ],
      "brandable": [
        "lyra",
        "zen",
        "bloom",
        "nova",
        "aura",
        "sol",
        "vera"
      ],
      "local": [
        "home",
        "craft",
        "studio",
        "hearth",
        "nook",
        "grove"
      ]
    },
    "brandableEndings": [
      "ly",
      "io",
      "ify",
      "ora",
      "ivo",
      "ela",
      "ia",
      "ico",
      "ova",
      "ara",
      "ely",
      "ium"
    ],
    "maxRootsForCombination": 20,
    "maxTrendsForCombination": 10,
    "maxTwoWordPool": 22
  },
  "lexicon": {
    "modifiers": [
      "apex",
      "blue",
      "bold",
      "brave",
      "bright",
      "brisk",
      "calm",
      "clean",
      "clear",
      "crisp",
      "deep",
      "easy",
      "fair",
      "fast",
      "fine",
      "firm",
      "first",
      "fresh",
      "glad",
      "glow",
      "good",
      "grand",
      "great",
      "green",
      "high",
      "ideal",
      "keen",
      "kind",
      "light",
      "live",
      "loyal",
      "lucid",
      "lush",
      "main",
      "mint",
      "neat",
      "new",
      "next",
      "noble",
      "open",
      "peak",
      "plain",
      "prime",
      "pure",
      "quick",
      "rapid",
      "rare",
      "real",
      "rich",
      "ripe",
      "safe",
      "sage",
      "sharp",
      "sheer",
      "sleek",
      "slim",
      "smart",
      "smooth",
      "soft",
      "solid",
      "sound",
      "steady",
      "still",
      "stout",
      "strong",
      "sure",
      "sweet",
      "swift",
      "tidy",
      "tight",
      "true",
      "urban",
      "vast",
      "vital",
      "vivid",
      "warm",
      "wide",
      "wild",
      "wise",
      "young",
      "zen"
    ],
    "headNouns": [
      "arc",
      "arch",
      "atlas",
      "axis",
      "bank",
      "base",
      "bay",
      "beam",
      "bench",
      "bloom",
      "board",
      "bolt",
      "bond",
      "book",
      "boost",
      "booth",
      "box",
      "brand",
      "brew",
      "bridge",
      "brook",
      "cabin",
      "cache",
      "camp",
      "cape",
      "card",
      "care",
      "cart",
      "case",
      "cash",
      "cell",
      "chain",
      "chart",
      "chase",
      "city",
      "claim",
      "cliff",
      "climb",
      "clinic",
      "cloud",
      "club",
      "coach",
      "coast",
      "code",
      "coin",
      "core",
      "cove",
      "craft",
      "crane",
      "crew",
      "crop",
      "cross",
      "crown",
      "cube",
      "curve",
      "cycle",
      "dash",
      "data",
      "deal",
      "deck",
      "desk",
      "dial",
      "dock",
      "dome",
      "door",
      "dose",
      "draft",
      "drive",
      "drop",
      "dune",
      "edge",
      "entry",
      "farm",
      "feed",
      "field",
      "file",
      "film",
      "fire",
      "fleet",
      "flint",
      "flow",
      "foam",
      "fold",
      "font",
      "food",
      "forge",
      "form",
      "frame",
      "fruit",
      "fuel",
      "gate",
      "gear",
      "gem",
      "gift",
      "glass",
      "globe",
      "goal",
      "grade",
      "grain",
      "grant",
      "grid",
      "grip",
      "grove",
      "guard",
      "guide",
      "hall",
      "hand",
      "haven",
      "hawk",
      "head",
      "health",
      "heart",
      "hearth",
      "hedge",
      "helm",
      "herd",
      "hive",
      "hollow",
      "home",
      "hook",
      "hope",
      "horn",
      "house",
      "hub",
      "index",
      "inlet",
      "iron",
      "isle",
      "jet",
      "key",
      "kit",
      "lab",
      "labs",
      "lake",
      "lamp",
      "land",
      "lane",
      "latch",
      "launch",
      "layer",
      "leaf",
      "league",
      "ledge",
      "lens",
      "level",
      "lift",
      "line",
      "link",
      "list",
      "loft",
      "loop",
      "mark",
      "market",
      "mason",
      "match",
      "meadow",
      "media",
      "mesh",
      "meter",
      "mill",
      "mind",
      "mine",
      "mode",
      "moon",
      "motion",
      "mount",
      "nest",
      "net",
      "nook",
      "north",
      "note",
      "oak",
      "oasis",
      "ocean",
      "orbit",
      "order",
      "page",
      "palm",
      "panel",
      "park",
      "patch",
      "path",
      "pearl",
      "phase",
      "pier",
      "pine",
      "pitch",
      "place",
      "plan",
      "plane",
      "plant",
      "plate",
      "plot",
      "point",
      "pond",
      "pool",
      "port",
      "post",
      "press",
      "price",
      "pride",
      "prism",
      "prize",
      "proof",
      "pulse",
      "quest",
      "quill",
      "quote",
      "rail",
      "ramp",
      "range",
      "rank",
      "rate",
      "reach",
      "realm",
      "reef",
      "reel",
      "rest",
      "ridge",
      "rise",
      "river",
      "road",
      "rock",
      "room",
      "root",
      "rope",
      "rose",
      "route",
      "ruby",
      "safe",
      "sail",
      "salt",
      "sand",
      "scale",
      "scope",
      "score",
      "scout",
      "seal",
      "seed",
      "sense",
      "serum",
      "shade",
      "shape",
      "share",
      "shed",
      "sheet",
      "shelf",
      "shell",
      "shield",
      "shift",
      "ship",
      "shop",
      "shore",
      "side",
      "sign",
      "silk",
      "site",
      "skill",
      "sky",
      "slate",
      "slope",
      "soil",
      "solar",
      "song",
      "sound",
      "source",
      "south",
      "space",
      "span",
      "spark",
      "spice",
      "spire",
      "spot",
      "spring",
      "sprout",
      "spur",
      "square",
      "stack",
      "staff",
      "stage",
      "stake",
      "stand",
      "star",
      "state",
      "steam",
      "steel",
      "stem",
      "step",
      "stitch",
      "stock",
      "stone",
      "store",
      "storm",
      "story",
      "strand",
      "stream",
      "street",
      "strip",
      "studio",
      "style",
      "summit",
      "sun",
      "supply",
      "surf",
      "swing",
      "table",
      "tag",
      "tank",
      "task",
      "team",
      "tempo",
      "tent",
      "term",
      "test",
      "thread",
      "tide",
      "tier",
      "tile",
      "time",
      "title",
      "token",
      "tone",
      "tool",
      "torch",
      "tour",
      "tower",
      "town",
      "trace",
      "track",
      "trade",
      "trail",
      "train",
      "tram",
      "trap",
      "tray",
      "treat",
      "tree",
      "trek",
      "trend",
      "tribe",
      "trim",
      "trove",
      "trust",
      "tube",
      "tune",
      "turn",
      "twin",
      "unit",
      "vale",
      "valley",
      "vault",
      "vein",
      "vessel",
      "view",
      "villa",
      "vine",
      "vista",
      "voice",
      "volt",
      "wagon",
      "walk",
      "wall",
      "ward",
      "ware",
      "watch",
      "water",
      "wave",
      "way",
      "weave",
      "web",
      "well",
      "wharf",
      "wheel",
      "wick",
      "wind",
      "wing",
      "wire",
      "wish",
      "wood",
      "work",
      "world",
      "yard",
      "yield",
      "zone"
    ],
    "nicheHeads": {
      "facial_skincare": [
        "serum",
        "glow",
        "skin",
        "care",
        "balm",
        "dew",
        "silk",
        "bloom",
        "radiance",
        "lume",
        "veil",
        "petal",
        "ritual"
      ],
      "beauty": [
        "glam",
        "gloss",
        "shine",
        "tone",
        "blush",
        "salon",
        "studio"
      ],
      "pet_wellness": [
        "paw",
        "pet",
        "tail",
        "fetch",
        "bark",
        "purr",
        "kennel",
        "collar",
        "treat",
        "vet"
      ],
      "sleep": [
        "sleep",
        "rest",
        "dream",
        "night",
        "calm",
        "doze",
        "pillow",
        "lull"
      ],
      "health": [
        "health",
        "vital",
        "care",
        "clinic",
        "wellness",
        "thrive",
        "heal"
      ],
      "longevity": [
        "span",
        "vital",
        "prime",
        "renew",
        "cell",
        "age",
        "youth"
      ],
      "finance": [
        "bank",
        "fund",
        "cash",
        "capital",
        "ledger",
        "vault",
        "yield",
        "mint"
      ],
      "crypto": [
        "chain",
        "block",
        "ledger",
        "token",
        "wallet",
        "node",
        "vault"
      ],
      "saas": [
        "stack",
        "flow",
        "sync",
        "deploy",
        "cloud",
        "desk",
        "board",
        "ops"
      ],
      "ai": [
        "mind",
        "neural",
        "agent",
        "model",
        "logic",
        "brain",
        "signal"
      ],
      "roofing": [
        "roof",
        "shingle",
        "eave",
        "gutter",
        "peak",
        "ridge",
        "crew"
      ],
      "fitness": [
        "fit",
        "rep",
        "lift",
        "train",
        "muscle",
        "form",
        "gym",
        "stride"
      ],
      "food": [
        "kitchen",
        "plate",
        "harvest",
        "spice",
        "table",
        "brew",
        "crumb"
      ],
      "travel": [
        "trip",
        "voyage",
        "roam",
        "wander",
        "escape",
        "route",
        "compass"
      ],
      "home": [
        "nest",
        "hearth",
        "abode",
        "dwell",
        "room",
        "porch",
        "tile"
      ]
    },
    "compoundTails": [
      "labs",
      "works",
      "supply",
      "goods",
      "studio",
      "group",
      "collective",
      "house",
      "market",
      "society",
      "guild",
      "co"
    ],
    "dictionary": [
      "abode",
      "age",
      "agent",
      "apex",
      "arc",
      "arch",
      "atlas",
      "aura",
      "axis",
      "balm",
      "bank",
      "bark",
      "base",
      "bay",
      "beam",
      "bench",
      "block",
      "bloom",
      "blue",
      "blush",
      "board",
      "bold",
      "bolt",
      "bond",
      "book",
      "boost",
      "booth",
      "box",
      "brain",
      "brand",
      "brave",
      "brew",
      "bridge",
      "bright",
      "brisk",
      "brook",
      "cabin",
      "cache",
      "calm",
      "camp",
      "cape",
      "capital",
      "card",
      "care",
      "cart",
      "case",
      "cash",
      "cell",
      "chain",
      "chart",
      "chase",
      "city",
      "claim",
      "clean",
      "clear",
      "cliff",
      "climb",
      "clinic",
      "cloud",
      "club",
      "co",
      "coach",
      "coast",
      "code",
      "coin",
      "collar",
      "collective",
      "compass",
      "core",
      "cove",
      "craft",
      "crane",
      "crest",
      "crew",
      "crisp",
      "crop",
      "cross",
      "crown",
      "crumb",
      "cube",
      "curve",
      "cycle",
      "dash",
      "data",
      "deal",
      "deck",
      "deep",
      "deploy",
      "desk",
      "dew",
      "dial",
      "dock",
      "dome",
      "door",
      "dose",
      "doze",
      "draft",
      "dream",
      "drive",
      "drop",
      "dune",
      "dwell",
      "easy",
      "eave",
      "edge",
      "elevate",
      "ember",
      "entry",
      "escape",
      "fair",
      "farm",
      "fast",
      "feed",
      "fetch",
      "field",
      "file",
      "film",
      "fine",
      "fire",
      "firm",
      "first",
      "fit",
      "fleet",
      "flint",
      "flow",
      "flux",
      "foam",
      "fold",
      "font",
      "food",
      "forge",
      "form",
      "frame",
      "fresh",
      "fruit",
      "fuel",
      "fund",
      "fuse",
      "gate",
      "gear",
      "gem",
      "gift",
      "glad",
      "glam",
      "glass",
      "globe",
      "gloss",
      "glow",
      "goal",
      "good",
      "goods",
      "grade",
      "grain",
      "grand",
      "grant",
      "great",
      "green",
      "grid",
      "grip",
      "group",
      "grove",
      "guard",
      "guide",
      "guild",
      "gutter",
      "gym",
      "hall",
      "halo",
      "hand",
      "harvest",
      "haven",
      "hawk",
      "head",
      "heal",
      "health",
      "heart",
      "hearth",
      "hedge",
      "helm",
      "herd",
      "high",
      "hive",
      "hollow",
      "home",
      "hook",
      "hope",
      "horizon",
      "horn",
      "house",
      "hub",
      "ideal",
      "ignite",
      "index",
      "inlet",
      "iron",
      "isle",
      "jet",
      "kairo",
      "keen",
      "kennel",
      "key",
      "kind",
      "kit",
      "kitchen",
      "lab",
      "labs",
      "lake",
      "lamp",
      "land",
      "lane",
      "latch",
      "launch",
      "layer",
      "leaf",
      "league",
      "ledge",
      "ledger",
      "lens",
      "level",
      "lift",
      "light",
      "line",
      "link",
      "list",
      "live",
      "loft",
      "logic",
      "loom",
      "loop",
      "loyal",
      "lucid",
      "lull",
      "lume",
      "lumen",
      "luna",
      "lush",
      "lyra",
      "main",
      "mark",
      "market",
      "mason",
      "match",
      "meadow",
      "media",
      "mesh",
      "meter",
      "mill",
      "mind",
      "mine",
      "mint",
      "mode",
      "model",
      "moon",
      "motion",
      "mount",
      "muscle",
      "nava",
      "neat",
      "nest",
      "net",
      "neural",
      "new",
      "next",
      "nexus",
      "night",
      "nilo",
      "noble",
      "node",
      "nook",
      "north",
      "note",
      "nova",
      "oak",
      "oasis",
      "ocean",
      "open",
      "ops",
      "orbit",
      "order",
      "orion",
      "page",
      "palm",
      "panel",
      "park",
      "patch",
      "path",
      "paw",
      "peak",
      "pearl",
      "pet",
      "petal",
      "phase",
      "pico",
      "pier",
      "pillow",
      "pilot",
      "pine",
      "pitch",
      "place",
      "plain",
      "plan",
      "plane",
      "plant",
      "plate",
      "plot",
      "point",
      "pond",
      "pool",
      "porch",
      "port",
      "post",
      "press",
      "price",
      "pride",
      "prime",
      "prism",
      "prize",
      "proof",
      "pulse",
      "pure",
      "purr",
      "quest",
      "quick",
      "quill",
      "quote",
      "radiance",
      "rail",
      "ramp",
      "range",
      "rank",
      "rapid",
      "rare",
      "rate",
      "reach",
      "real",
      "realm",
      "reef",
      "reel",
      "renew",
      "rep",
      "rest",
      "rich",
      "ridge",
      "ripe",
      "rise",
      "ritual",
      "river",
      "road",
      "roam",
      "rock",
      "roof",
      "room",
      "root",
      "rope",
      "rose",
      "route",
      "ruby",
      "safe",
      "sage",
      "sail",
      "salon",
      "salt",
      "sand",
      "scale",
      "scope",
      "score",
      "scout",
      "seal",
      "seed",
      "sense",
      "serum",
      "shade",
      "shape",
      "share",
      "sharp",
      "shed",
      "sheer",
      "sheet",
      "shelf",
      "shell",
      "shield",
      "shift",
      "shine",
      "shingle",
      "ship",
      "shop",
      "shore",
      "side",
      "sign",
      "signal",
      "silk",
      "site",
      "skill",
      "skin",
      "sky",
      "slate",
      "sleek",
      "sleep",
      "slim",
      "slope",
      "smart",
      "smooth",
      "society",
      "soft",
      "soil",
      "sol",
      "solar",
      "solid",
      "song",
      "sound",
      "source",
      "south",
      "space",
      "span",
      "spark",
      "spice",
      "spire",
      "spot",
      "spring",
      "sprout",
      "spur",
      "square",
      "stack",
      "staff",
      "stage",
      "stake",
      "stand",
      "star",
      "state",
      "steady",
      "steam",
      "steel",
      "stem",
      "step",
      "still",
      "stitch",
      "stock",
      "stone",
      "store",
      "storm",
      "story",
      "stout",
      "strand",
      "stream",
      "street",
      "stride",
      "strip",
      "strong",
      "studio",
      "style",
      "suite",
      "summit",
      "sun",
      "supply",
      "sure",
      "surf",
      "sweet",
      "swift",
      "swing",
      "sync",
      "table",
      "tag",
      "tail",
      "tank",
      "task",
      "team",
      "tempo",
      "tent",
      "term",
      "test",
      "thread",
      "thrive",
      "tide",
      "tidy",
      "tier",
      "tight",
      "tile",
      "time",
      "title",
      "token",
      "tone",
      "tool",
      "torch",
      "tour",
      "tower",
      "town",
      "trace",
      "track",
      "trade",
      "trail",
      "train",
      "tram",
      "trap",
      "tray",
      "treat",
      "tree",
      "trek",
      "trend",
      "tribe",
      "trim",
      "trip",
      "trove",
      "true",
      "trust",
      "tube",
      "tune",
      "turn",
      "twin",
      "unit",
      "urban",
      "vale",
      "valley",
      "vast",
      "vault",
      "veil",
      "vein",
      "vera",
      "vertex",
      "vessel",
      "vet",
      "vibe",
      "view",
      "villa",
      "vine",
      "vista",
      "vital",
      "vivid",
      "voice",
      "volt",
      "voyage",
      "wagon",
      "walk",
      "wall",
      "wallet",
      "wander",
      "ward",
      "ware",
      "warm",
      "watch",
      "water",
      "wave",
      "way",
      "weave",
      "web",
      "well",
      "wellness",
      "wharf",
      "wheel",
      "wick",
      "wide",
      "wild",
      "wind",
      "wing",
      "wire",
      "wise",
      "wish",
      "wood",
      "work",
      "works",
      "world",
      "yard",
      "yield",
      "young",
      "youth",
      "zara",
      "zen",
      "zenith",
      "zone"
    ]
  },
  "phoneticFragments": [
    "ly",
    "ra",
    "vo",
    "xa",
    "ko",
    "ni",
    "ze",
    "io",
    "ora",
    "ela",
    "on",
    "en",
    "iq",
    "ex",
    "um"
  ],
  "profiles": [
    {
      "key": "longevity",
      "display_name": "Longevity",
      "aliases": [
        "longevity",
        "healthspan",
        "lifespan",
        "antiaging",
        "anti-aging",
        "biohacking",
        "biohack",
        "aging",
        "senescence"
      ],
      "positive_words": [
        "vitality",
        "span",
        "thrive",
        "prime",
        "bloom",
        "well",
        "bio",
        "pulse",
        "revive",
        "renew",
        "lumen",
        "aura",
        "vita",
        "forge",
        "apex",
        "zenith",
        "sol",
        "nova",
        "rise",
        "core",
        "flow",
        "spark",
        "helix",
        "opti",
        "nourish",
        "balance",
        "clarity",
        "longevity",
        "healthspan",
        "evera",
        "vivara",
        "alyra",
        "nuvia",
        "elara"
      ],
      "avoid_words": [
        "cure",
        "miracle",
        "immortal",
        "immortality",
        "forever",
        "elixir",
        "fountain",
        "youthserum",
        "antiage",
        "botox",
        "wrinkle",
        "hackdeath",
        "godmode",
        "supercure"
      ],
      "avoid_patterns": [
        "xxx",
        "free",
        "cheap",
        "spam"
      ],
      "tone": [
        "premium",
        "trustworthy",
        "health-focused",
        "modern",
        "aspirational"
      ],
      "buyer_archetypes": [
        "supplement brand",
        "longevity clinic",
        "health optimization startup",
        "newsletter / media brand",
        "wellness marketplace"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "Avoid medical-claim spam and immortality tropes; prefer calm premium vitality language.",
      "seed_keywords": [
        "vita",
        "span",
        "prime",
        "bloom",
        "lumen",
        "revive"
      ],
      "selector_visible": true
    },
    {
      "key": "house_flipping",
      "display_name": "House flipping",
      "aliases": [
        "house flipping",
        "houseflipping",
        "flip",
        "fixer",
        "rehab"
      ],
      "positive_words": [
        "flip",
        "reno",
        "forge",
        "nest",
        "haven",
        "prime",
        "craft",
        "rise",
        "apex",
        "dwell",
        "hearth",
        "lodge",
        "vista",
        "ridge",
        "grove"
      ],
      "avoid_words": [
        "slumlord",
        "getrich",
        "scamflip",
        "cheapfix"
      ],
      "avoid_patterns": [],
      "tone": [
        "practical",
        "premium",
        "trustworthy",
        "modern"
      ],
      "buyer_archetypes": [
        "house flipper brand",
        "reno media / newsletter",
        "investor education product",
        "contractor marketplace"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "flip",
        "reno",
        "nest",
        "craft",
        "ridge",
        "haven"
      ],
      "selector_visible": true
    },
    {
      "key": "real_estate",
      "display_name": "Real estate",
      "aliases": [
        "real estate",
        "realestate",
        "realty",
        "property",
        "broker",
        "homes"
      ],
      "positive_words": [
        "home",
        "nest",
        "haven",
        "lodge",
        "vista",
        "prime",
        "estate",
        "dwell",
        "grove",
        "ridge",
        "aura",
        "lumen",
        "craft",
        "trust",
        "key"
      ],
      "avoid_words": [
        "mlsleak",
        "scamhome",
        "spamlisting"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "premium",
        "clean",
        "aspirational"
      ],
      "buyer_archetypes": [
        "brokerage brand",
        "proptech startup",
        "home services marketplace",
        "real estate media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "home",
        "nest",
        "haven",
        "vista",
        "prime",
        "key"
      ],
      "selector_visible": true
    },
    {
      "key": "local_service",
      "display_name": "Local service",
      "aliases": [
        "local service",
        "localservice",
        "home service",
        "contractor",
        "trades"
      ],
      "positive_words": [
        "home",
        "care",
        "pro",
        "craft",
        "trust",
        "swift",
        "prime",
        "local",
        "handy",
        "fix",
        "nest",
        "glow",
        "bright",
        "clear"
      ],
      "avoid_words": [
        "cheapjob",
        "spamfix",
        "scampro"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "friendly",
        "practical",
        "local"
      ],
      "buyer_archetypes": [
        "local service company",
        "home services marketplace",
        "franchise brand",
        "lead-gen tool"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "home",
        "pro",
        "craft",
        "trust",
        "swift",
        "care"
      ],
      "selector_visible": true
    },
    {
      "key": "roofing",
      "display_name": "Roofing",
      "aliases": [
        "roofing",
        "roofer",
        "roof",
        "shingle"
      ],
      "positive_words": [
        "roof",
        "ridge",
        "peak",
        "shield",
        "cover",
        "prime",
        "apex",
        "craft",
        "trust",
        "fort",
        "guard",
        "rise",
        "summit"
      ],
      "avoid_words": [
        "leaky",
        "scamroof",
        "cheapshingle"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "strong",
        "local",
        "premium"
      ],
      "buyer_archetypes": [
        "roofing contractor",
        "home services franchise",
        "local lead brand"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "roof",
        "ridge",
        "peak",
        "shield",
        "apex",
        "craft"
      ],
      "selector_visible": true
    },
    {
      "key": "plumbing",
      "display_name": "Plumbing",
      "aliases": [
        "plumbing",
        "plumber",
        "pipes",
        "drain"
      ],
      "positive_words": [
        "pipe",
        "flow",
        "drain",
        "clear",
        "prime",
        "swift",
        "trust",
        "craft",
        "aqua",
        "pulse",
        "forge",
        "pro",
        "flush"
      ],
      "avoid_words": [
        "clogspam",
        "scampipe",
        "cheapplumb"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "practical",
        "local",
        "clean"
      ],
      "buyer_archetypes": [
        "plumbing company",
        "home services franchise",
        "emergency repair brand"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "flow",
        "pipe",
        "clear",
        "aqua",
        "swift",
        "pro"
      ],
      "selector_visible": true
    },
    {
      "key": "hvac",
      "display_name": "HVAC",
      "aliases": [
        "hvac",
        "heating",
        "cooling",
        "aircon",
        "furnace",
        "ac"
      ],
      "positive_words": [
        "air",
        "cool",
        "warm",
        "climate",
        "breeze",
        "prime",
        "flow",
        "clear",
        "trust",
        "swift",
        "aura",
        "pulse",
        "forge"
      ],
      "avoid_words": [
        "scamac",
        "cheaphvac",
        "spamheat"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "modern",
        "local",
        "clean"
      ],
      "buyer_archetypes": [
        "HVAC contractor",
        "home comfort brand",
        "service franchise"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "air",
        "cool",
        "breeze",
        "flow",
        "climate",
        "prime"
      ],
      "selector_visible": true
    },
    {
      "key": "ai",
      "display_name": "AI / Automation",
      "aliases": [
        "ai",
        "ml",
        "gpt",
        "llm",
        "neural",
        "agent",
        "genai",
        "automation"
      ],
      "positive_words": [
        "nova",
        "neural",
        "mind",
        "oracle",
        "sense",
        "prompt",
        "spark",
        "aura",
        "lumen",
        "agent",
        "intel",
        "logic",
        "signal",
        "prism",
        "forge",
        "atlas",
        "auto",
        "pilot"
      ],
      "avoid_words": [
        "botspam",
        "deepfake",
        "skynet",
        "terminator",
        "hackai"
      ],
      "avoid_patterns": [],
      "tone": [
        "futuristic",
        "intelligent",
        "premium",
        "startup-like"
      ],
      "buyer_archetypes": [
        "AI product company",
        "agent / automation startup",
        "developer tooling",
        "research brand"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "nova",
        "agent",
        "spark",
        "signal",
        "forge",
        "pilot"
      ],
      "selector_visible": true
    },
    {
      "key": "creator",
      "display_name": "Creator tools",
      "aliases": [
        "creator",
        "creator tools",
        "creators",
        "newsletter",
        "studio",
        "audience"
      ],
      "positive_words": [
        "cast",
        "signal",
        "bloom",
        "spark",
        "aura",
        "pulse",
        "story",
        "forge",
        "studio",
        "craft",
        "rise",
        "lumen",
        "orbit",
        "nova"
      ],
      "avoid_words": [
        "fakefollower",
        "spamgrow",
        "botfarm"
      ],
      "avoid_patterns": [],
      "tone": [
        "modern",
        "creative",
        "aspirational",
        "startup-like"
      ],
      "buyer_archetypes": [
        "creator tooling startup",
        "newsletter / media brand",
        "course creator product",
        "audience growth tool"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "cast",
        "spark",
        "studio",
        "pulse",
        "craft",
        "bloom"
      ],
      "selector_visible": true
    },
    {
      "key": "wellness",
      "display_name": "Wellness",
      "aliases": [
        "wellness",
        "calm",
        "recovery",
        "mindfulness",
        "selfcare"
      ],
      "positive_words": [
        "calm",
        "rest",
        "bloom",
        "aura",
        "flow",
        "zen",
        "lumen",
        "solace",
        "balance",
        "thrive",
        "nourish",
        "vita",
        "pulse",
        "revive"
      ],
      "avoid_words": [
        "cure",
        "miracle",
        "guaranteed",
        "spamwell"
      ],
      "avoid_patterns": [],
      "tone": [
        "calm",
        "premium",
        "trustworthy",
        "aspirational"
      ],
      "buyer_archetypes": [
        "wellness consumer brand",
        "recovery / sleep product",
        "mindfulness app",
        "wellness media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "calm",
        "bloom",
        "aura",
        "flow",
        "lumen",
        "balance"
      ],
      "selector_visible": true
    },
    {
      "key": "facial_skincare",
      "display_name": "Women's facial / skincare",
      "aliases": [
        "facial",
        "facials",
        "skincare",
        "skin care",
        "skincare addiction",
        "womens facial",
        "women's facial",
        "womens facial products",
        "women's facial products",
        "face care",
        "beauty",
        "serum",
        "moisturizer",
        "glow",
        "derm",
        "clean beauty"
      ],
      "positive_words": [
        "glow",
        "dew",
        "luma",
        "lume",
        "vera",
        "petal",
        "silk",
        "aura",
        "bloom",
        "nira",
        "lumen",
        "soft",
        "pure",
        "calm",
        "veil",
        "rose",
        "mira",
        "nouri",
        "elara",
        "solis",
        "vita",
        "flora",
        "luca"
      ],
      "avoid_words": [
        "cure",
        "miracle",
        "botox",
        "whitening",
        "bleach",
        "cheapserum",
        "wrinklefree",
        "guaranteed"
      ],
      "avoid_patterns": [
        "xxx",
        "free",
        "cheap",
        "spam"
      ],
      "tone": [
        "premium",
        "clean",
        "calm",
        "feminine",
        "trustworthy"
      ],
      "buyer_archetypes": [
        "DTC facial / skincare brand",
        "esthetician / facial spa",
        "clean beauty marketplace",
        "derm-cosmetic product line"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "Premium women's facial products \u2014 glow and ritual language, no medical-claim spam.",
      "seed_keywords": [
        "glow",
        "luma",
        "dew",
        "petal",
        "vera",
        "silk"
      ],
      "selector_visible": true
    },
    {
      "key": "diagnostics",
      "display_name": "Diagnostics",
      "aliases": [
        "diagnostics",
        "diagnostic",
        "lab",
        "testing",
        "biomarker"
      ],
      "positive_words": [
        "lab",
        "signal",
        "prism",
        "clarity",
        "pulse",
        "helix",
        "lumen",
        "sense",
        "opti",
        "forge",
        "nova",
        "core",
        "trace"
      ],
      "avoid_words": [
        "fakelab",
        "miracle",
        "scamtest",
        "guaranteed"
      ],
      "avoid_patterns": [],
      "tone": [
        "clinical",
        "trustworthy",
        "modern",
        "premium"
      ],
      "buyer_archetypes": [
        "diagnostics startup",
        "lab / testing brand",
        "healthtech product",
        "biomarker media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "lab",
        "signal",
        "clarity",
        "pulse",
        "helix",
        "lumen"
      ],
      "selector_visible": true
    },
    {
      "key": "supplements",
      "display_name": "Supplements",
      "aliases": [
        "supplements",
        "supplement",
        "nutra",
        "vitamins",
        "nootropic"
      ],
      "positive_words": [
        "vita",
        "nourish",
        "prime",
        "bloom",
        "pulse",
        "opti",
        "forge",
        "aura",
        "lumen",
        "thrive",
        "balance",
        "spark",
        "core",
        "rise"
      ],
      "avoid_words": [
        "cure",
        "miracle",
        "steroidspam",
        "guaranteed"
      ],
      "avoid_patterns": [],
      "tone": [
        "premium",
        "health-focused",
        "aspirational",
        "trustworthy"
      ],
      "buyer_archetypes": [
        "supplement brand",
        "DTC wellness product",
        "performance nutrition startup",
        "health media"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "vita",
        "prime",
        "nourish",
        "opti",
        "bloom",
        "pulse"
      ],
      "selector_visible": true
    },
    {
      "key": "legal",
      "display_name": "Legal",
      "aliases": [
        "legal",
        "law",
        "attorney",
        "lawyer",
        "counsel"
      ],
      "positive_words": [
        "counsel",
        "trust",
        "clear",
        "prime",
        "lex",
        "forge",
        "apex",
        "guard",
        "shield",
        "justice",
        "path",
        "clarity",
        "firm"
      ],
      "avoid_words": [
        "scamlaw",
        "fakecase",
        "spamlegal"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "premium",
        "clear",
        "professional"
      ],
      "buyer_archetypes": [
        "law firm brand",
        "legal tech startup",
        "consumer legal product",
        "compliance tool"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "lex",
        "trust",
        "clear",
        "counsel",
        "prime",
        "shield"
      ],
      "selector_visible": true
    },
    {
      "key": "finance",
      "display_name": "Finance",
      "aliases": [
        "finance",
        "fintech",
        "banking",
        "payments",
        "capital",
        "wealth",
        "pay"
      ],
      "positive_words": [
        "pay",
        "vault",
        "ledger",
        "fund",
        "trust",
        "capital",
        "mint",
        "cash",
        "clear",
        "prime",
        "apex",
        "folio",
        "treasury",
        "swift",
        "bridge"
      ],
      "avoid_words": [
        "scam",
        "ponzi",
        "getrich",
        "loot",
        "cashgrab",
        "spamcash"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "premium",
        "secure",
        "modern"
      ],
      "buyer_archetypes": [
        "payments startup",
        "wealth / investing brand",
        "SMB finance tool",
        "neo-bank"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "pay",
        "vault",
        "trust",
        "mint",
        "clear",
        "folio"
      ],
      "selector_visible": true
    },
    {
      "key": "saas",
      "display_name": "SaaS / B2B Software",
      "aliases": [
        "saas",
        "software",
        "b2b",
        "workspace",
        "productivity",
        "ops"
      ],
      "positive_words": [
        "flow",
        "sync",
        "pilot",
        "ops",
        "dash",
        "launch",
        "stack",
        "hub",
        "path",
        "grid",
        "base",
        "desk",
        "craft",
        "forge",
        "pulse",
        "orbit",
        "nova",
        "clear",
        "swift",
        "lean"
      ],
      "avoid_words": [
        "freebie",
        "crack",
        "warez",
        "spam",
        "cheapsoft",
        "nulled"
      ],
      "avoid_patterns": [],
      "tone": [
        "modern",
        "efficient",
        "startup-like",
        "clean"
      ],
      "buyer_archetypes": [
        "B2B SaaS founder",
        "productivity tool",
        "ops / internal tools startup",
        "developer platform"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "flow",
        "sync",
        "stack",
        "pilot",
        "clear",
        "orbit"
      ],
      "selector_visible": false
    },
    {
      "key": "health",
      "display_name": "Health & Wellness",
      "aliases": [
        "health",
        "care",
        "medical",
        "clinic",
        "fitness"
      ],
      "positive_words": [
        "vita",
        "pulse",
        "heal",
        "care",
        "life",
        "well",
        "bloom",
        "lumen",
        "balance",
        "nourish",
        "thrive",
        "calm",
        "revive",
        "prime",
        "flow"
      ],
      "avoid_words": [
        "cure",
        "miracle",
        "guaranteed",
        "instantheal",
        "drugspam"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "calm",
        "health-focused",
        "premium"
      ],
      "buyer_archetypes": [
        "clinic / practice brand",
        "wellness consumer brand",
        "health tech startup",
        "fitness media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "vita",
        "pulse",
        "care",
        "bloom",
        "thrive",
        "calm"
      ],
      "selector_visible": false
    },
    {
      "key": "crypto",
      "display_name": "Crypto / Web3",
      "aliases": [
        "crypto",
        "web3",
        "blockchain",
        "defi",
        "nft",
        "token"
      ],
      "positive_words": [
        "vault",
        "chain",
        "mint",
        "node",
        "spark",
        "flux",
        "prime",
        "orbit",
        "ledger",
        "bridge",
        "signal",
        "forge"
      ],
      "avoid_words": [
        "rug",
        "pump",
        "moonshotspam",
        "shitcoin",
        "scamcoin"
      ],
      "avoid_patterns": [],
      "tone": [
        "modern",
        "technical",
        "startup-like"
      ],
      "buyer_archetypes": [
        "protocol / wallet brand",
        "crypto media",
        "DeFi product",
        "NFT / digital goods brand"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "vault",
        "mint",
        "chain",
        "orbit",
        "signal",
        "forge"
      ],
      "selector_visible": false
    },
    {
      "key": "commerce",
      "display_name": "E-commerce / Retail",
      "aliases": [
        "commerce",
        "ecommerce",
        "shop",
        "retail",
        "store",
        "dtc"
      ],
      "positive_words": [
        "shop",
        "cart",
        "trade",
        "deal",
        "store",
        "market",
        "swift",
        "craft",
        "bloom",
        "prime",
        "nest",
        "haven"
      ],
      "avoid_words": [
        "fakeshop",
        "cheapcrap",
        "spamdeal",
        "knockoff"
      ],
      "avoid_patterns": [],
      "tone": [
        "friendly",
        "commercial",
        "clean"
      ],
      "buyer_archetypes": [
        "DTC brand",
        "marketplace",
        "retail media",
        "shop tooling startup"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "shop",
        "craft",
        "nest",
        "swift",
        "bloom",
        "prime"
      ],
      "selector_visible": false
    },
    {
      "key": "education",
      "display_name": "Education / Learning",
      "aliases": [
        "education",
        "edtech",
        "learn",
        "course",
        "tutoring",
        "school"
      ],
      "positive_words": [
        "learn",
        "skill",
        "mind",
        "study",
        "spark",
        "path",
        "rise",
        "lumen",
        "quest",
        "forge",
        "clarity",
        "primer"
      ],
      "avoid_words": [
        "cheat",
        "essaymill",
        "fakecert",
        "spamcourse"
      ],
      "avoid_patterns": [],
      "tone": [
        "aspirational",
        "clear",
        "trustworthy",
        "modern"
      ],
      "buyer_archetypes": [
        "edtech startup",
        "course creator brand",
        "tutoring marketplace",
        "learning media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "learn",
        "spark",
        "path",
        "quest",
        "clarity",
        "rise"
      ],
      "selector_visible": false
    },
    {
      "key": "climate",
      "display_name": "Climate / Sustainability",
      "aliases": [
        "climate",
        "green",
        "sustainability",
        "carbon",
        "cleantech",
        "esg"
      ],
      "positive_words": [
        "green",
        "solar",
        "terra",
        "leaf",
        "grove",
        "orbit",
        "clear",
        "pure",
        "bloom",
        "forge",
        "volt",
        "tide"
      ],
      "avoid_words": [
        "greenwash",
        "fakecarbon",
        "pollutespam"
      ],
      "avoid_patterns": [],
      "tone": [
        "earnest",
        "modern",
        "premium",
        "trustworthy"
      ],
      "buyer_archetypes": [
        "climate tech startup",
        "sustainable consumer brand",
        "carbon / energy product",
        "impact media"
      ],
      "prefer_short": true,
      "max_label_length": 10,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "terra",
        "solar",
        "grove",
        "volt",
        "pure",
        "tide"
      ],
      "selector_visible": false
    },
    {
      "key": "fintech",
      "display_name": "Fintech / Payments",
      "aliases": [
        "fintech",
        "payments",
        "banking",
        "paytech"
      ],
      "positive_words": [
        "pay",
        "vault",
        "ledger",
        "fund",
        "trust",
        "capital",
        "mint",
        "clear",
        "prime",
        "folio",
        "swift",
        "bridge"
      ],
      "avoid_words": [
        "scam",
        "ponzi",
        "getrich",
        "loot",
        "cashgrab"
      ],
      "avoid_patterns": [],
      "tone": [
        "trustworthy",
        "premium",
        "secure",
        "modern"
      ],
      "buyer_archetypes": [
        "payments startup",
        "wealth brand",
        "SMB finance tool"
      ],
      "prefer_short": true,
      "max_label_length": 9,
      "min_label_length": 6,
      "preferred_patterns": [
        "two_word",
        "keyword_root",
        "keyword_suffix",
        "keyword_trend"
      ],
      "notes": "",
      "seed_keywords": [
        "pay",
        "vault",
        "mint",
        "clear",
        "folio",
        "swift"
      ],
      "selector_visible": false
    }
  ],
  "genericProfile": {
    "key": "custom",
    "display_name": "Other / custom",
    "aliases": [
      "brandable",
      "brand",
      "startup",
      "custom",
      "other"
    ],
    "positive_words": [
      "lyra",
      "zen",
      "bloom",
      "nova",
      "aura",
      "lumen",
      "orbit",
      "sol",
      "vera",
      "nilo",
      "forge",
      "prime",
      "apex",
      "spark"
    ],
    "avoid_words": [
      "xxx",
      "spam",
      "cheap",
      "freebie",
      "hackz"
    ],
    "avoid_patterns": [],
    "tone": [
      "premium",
      "modern",
      "clean"
    ],
    "buyer_archetypes": [
      "startup brand",
      "consumer product",
      "media brand"
    ],
    "prefer_short": true,
    "max_label_length": 10,
    "min_label_length": 6,
    "preferred_patterns": [
      "two_word",
      "keyword_root",
      "keyword_suffix",
      "keyword_trend"
    ],
    "notes": "",
    "seed_keywords": [
      "lyra",
      "nova",
      "aura",
      "lumen",
      "forge",
      "prime"
    ],
    "selector_visible": true
  },
  "selectorNicheKeys": [
    "longevity",
    "house_flipping",
    "real_estate",
    "local_service",
    "roofing",
    "plumbing",
    "hvac",
    "ai",
    "creator",
    "wellness",
    "facial_skincare",
    "diagnostics",
    "supplements",
    "legal",
    "finance"
  ],
  "scoring": {
    "weights": {
      "brandability": "0.24",
      "commercial_value": "0.20",
      "market_demand": "0.20",
      "domain_quality": "0.18",
      "flip_potential": "0.18",
      "risk_penalty": "0.10"
    },
    "rules": {
      "brandability_base": 50.0,
      "brandability_alpha_bonus": 15.0,
      "brandability_dirty_penalty": 24.0,
      "brandability_ideal_syllable_bonus": 12.0,
      "brandability_short_syllable_bonus": 5.0,
      "brandability_long_syllable_penalty": 14.0,
      "brandability_ideal_length_bonus": 12.0,
      "brandability_short_length_bonus": 8.0,
      "brandability_long_length_penalty": 18.0,
      "brandability_vowel_balance_bonus": 9.0,
      "brandability_low_vowel_penalty": 12.0,
      "brandability_cluster_penalty": 10.0,
      "brandability_repeat_penalty": 14.0,
      "brandability_brandable_end_bonus": 5.0,
      "brandability_clean_short_bonus": 12.0,
      "commercial_base": 46.0,
      "commercial_com_bonus": 24.0,
      "commercial_premium_tld_bonus": 16.0,
      "commercial_secondary_tld_bonus": 8.0,
      "commercial_obscure_tld_penalty": 8.0,
      "commercial_suffix_bonus_each": 6.0,
      "commercial_suffix_bonus_cap": 14.0,
      "commercial_compact_bonus": 8.0,
      "commercial_keyword_full_bonus": 14.0,
      "commercial_keyword_partial_bonus": 8.0,
      "commercial_industry_bonus": 6.0,
      "market_base": 50.0,
      "market_brandable_com_bonus": 8.0,
      "market_trend_bonus_each": 8.0,
      "market_trend_bonus_cap": 24.0,
      "market_keyword_full_bonus": 18.0,
      "market_keyword_partial_bonus": 10.0,
      "market_industry_bonus": 10.0,
      "market_modern_tld_bonus": 10.0,
      "market_short_bonus": 7.0,
      "market_live_trend_bonus_max": 12.0,
      "market_live_trend_up_multiplier": 1.08,
      "flip_live_trend_bonus_max": 6.0,
      "quality_base": 56.0,
      "quality_ideal_length_bonus": 18.0,
      "quality_long_penalty": 20.0,
      "quality_alpha_bonus": 12.0,
      "quality_hyphen_penalty": 12.0,
      "quality_number_penalty": 10.0,
      "quality_syllable_bonus": 8.0,
      "quality_cluster_penalty": 8.0,
      "quality_clean_short_bonus": 10.0,
      "flip_base": 40.0,
      "flip_com_bonus": 24.0,
      "flip_com_short_bonus": 12.0,
      "flip_premium_tld_bonus": 19.0,
      "flip_compact_alpha_bonus": 16.0,
      "flip_trend_bonus": 10.0,
      "flip_suffix_bonus": 8.0,
      "flip_dirty_penalty": 14.0,
      "risk_term_penalty_each": 35.0,
      "risk_term_penalty_cap": 50.0,
      "risk_number_penalty": 18.0,
      "risk_hyphen_penalty": 14.0,
      "risk_extreme_length_penalty": 24.0,
      "risk_long_length_penalty": 12.0,
      "risk_obscure_tld_penalty": 12.0,
      "risk_repeat_penalty": 14.0,
      "risk_cluster_penalty": 8.0,
      "risk_low_quality_pattern_penalty": 16.0,
      "niche_fit_base": 52.0,
      "niche_fit_positive_bonus_each": 10.0,
      "niche_fit_positive_bonus_cap": 28.0,
      "niche_fit_no_positive_penalty": 8.0,
      "niche_fit_avoid_penalty_each": 18.0,
      "niche_fit_avoid_penalty_cap": 40.0,
      "niche_fit_short_clean_bonus": 8.0,
      "niche_fit_overlong_penalty": 10.0,
      "niche_fit_tone_ending_bonus": 4.0,
      "niche_fit_tone_clash_penalty": 12.0,
      "niche_fit_market_blend": 0.22,
      "niche_risk_avoid_each": 12.0,
      "niche_risk_avoid_cap": 30.0
    },
    "premiumTlds": [
      "ai",
      "co",
      "com",
      "io"
    ],
    "secondaryTlds": [
      "app",
      "dev",
      "net",
      "org",
      "tech"
    ],
    "modernTlds": [
      "ai",
      "app",
      "dev",
      "io",
      "tech"
    ],
    "trendKeywords": [
      "ai",
      "auto",
      "cloud",
      "crypto",
      "data",
      "dev",
      "digital",
      "fin",
      "health",
      "learn",
      "market",
      "pay",
      "smart",
      "sync",
      "tech"
    ],
    "highRiskTerms": [
      "adidas",
      "adobe",
      "airbnb",
      "amazon",
      "apple",
      "chatgpt",
      "cisco",
      "disney",
      "facebook",
      "google",
      "instagram",
      "intel",
      "mastercard",
      "mcdonalds",
      "meta",
      "microsoft",
      "netflix",
      "nike",
      "nvidia",
      "openai",
      "oracle",
      "paypal",
      "samsung",
      "spotify",
      "starbucks",
      "tesla",
      "tiktok",
      "twitter",
      "uber",
      "visa",
      "walmart",
      "youtube"
    ],
    "commercialSuffixes": [
      "app",
      "base",
      "cloud",
      "desk",
      "flow",
      "hub",
      "ify",
      "io",
      "labs",
      "ly",
      "market",
      "path",
      "pay",
      "shop",
      "stack",
      "zone"
    ],
    "brandableEndings": [
      "a",
      "o",
      "ly",
      "io",
      "fy",
      "hub",
      "labs"
    ],
    "lengths": {
      "idealMin": 4,
      "idealMax": 12,
      "shortMax": 8,
      "compactMax": 10,
      "longMin": 15,
      "extremeMin": 19
    },
    "thresholds": {
      "strong": "72",
      "weak": "45",
      "highRisk": "30",
      "bandExcellent": "80",
      "bandStrong": "65",
      "bandModerate": "45"
    }
  }
};
